swagger: "2.0"
info:
  title: API server for Apinuts
  version: "0.1"
basePath: "/api/v1/"
consumes:
  - application/json
produces:
  - application/json

paths:
  /run-flow:
    post:
      tags: [Flow]
      operationId: selinon_api.api_v1.post_run_flow
      summary: Run a flow
      parameters:
        - $ref: "#/parameters/flow_name"
        - $ref: "#/parameters/node_args"
      responses:
        201:
          description: Flow was scheduled
  /transactions:
    post:
      tags: [Transactions]
      operationId: selinon_api.api_v1.post_transactions
      summary: Create a transaction
      parameters:
        - $ref: "#/parameters/title"
        - $ref: "#/parameters/currency"
        - $ref: "#/parameters/second_party"
        - $ref: "#/parameters/category"
        - $ref: "#/parameters/amount"
      responses:
        200:
          description: Transaction has been recorded
    get:
      tags: [Transactions]
      operationId: selinon_api.api_v1.get_transactions
      summary: Get a list of transactions
      responses:
        200:
          description: List of all transactions
  /categories/{category}/transactions:
    get:
      tags: [Categories]
      operationId: selinon_api.api_v1.get_transactions_per_category
      summary: Get transaction for category
      parameters:
        - $ref: "#/parameters/category_in_path"
      responses:
        200:
          description: Transaction for given category
  /categories:
    post:
      tags: [Categories]
      operationId: selinon_api.api_v1.post_categories
      summary: Create a category
      parameters:
        - $ref: "#/parameters/name"
        - $ref: "#/parameters/hidden"
      responses:
        200:
          description: Category has been recorded
    get:
      tags: [Categories]
      operationId: selinon_api.api_v1.get_categories
      summary: Get list of categories
      responses:
        200:
          description: List of categories 
  /budgets:
    post:
      tags: [Budgets]
      operationId: selinon_api.api_v1.post_budgets
      summary: Create a budget
      parameters:
        - $ref: "#/parameters/category"
        - $ref: "#/parameters/month"
        - $ref: "#/parameters/year"
        - $ref: "#/parameters/amount"
      responses:
        200:
          description: Budget has been recorded
    get:
      tags: [Budgets]
      operationId: selinon_api.api_v1.get_budgets
      summary: Get list of budgets
      responses:
        200:
          description: List of categories 

parameters:
  flow_name:
    name: flow_name
    in: query
    required: true
    description: Flow name
    type: string
  node_args:
    name: node_args
    in: body
    required: false
    description: Flow arguments
    schema:
      $ref: "#/definitions/QueryKwargs"
  title:
    name: title
    in: query
    required: true
    description: Title of transaction
    type: string
  second_party:
    name: second_party
    in: query
    required: true
    description: Second party of transaction
    type: string
  currency:
    name: currency
    in: query
    required: true
    description: Currency of transaction
    type: string
  category:
    name: category
    in: query
    required: true
    description: Category of transaction
    type: string
  amount:
    name: amount
    in: query
    required: true
    description: Amount of transaction
    type: number
  name:
    name: name
    in: query
    required: true
    description: Category name
    type: string
  hidden:
    name: hidden
    in: query
    required: true
    description: Is category hidden
    type: boolean
    default: false
  category_in_path:
    name: category
    in: path
    required: true
    description: Category name
    type: string
  month:
    name: month
    in: query
    required: true
    description: Budget month
    type: number
  year:
    name: year
    in: query
    required: true
    description: Budget year
    type: number

definitions:
  QueryKwargs:
    type: object
    additionalProperties: true
    example:
      foo: "bar"